#! /bin/sh

# Launch all the background programs.
pidof sxhkd || sxhkd &
# pidof dunst || dunst &
# pidof picom || picom &
# pidof emacs || emacs --daemon &
# pidof bspswallow || bspswallow &
pidof polybar && killall polybar
polybar bar0 &

# Disable Trackpad
# touchPadID=$(xinput | grep "TouchPad" | awk '{print substr($6,4,2)}')
# xinput set-prop $touchPadID "Device Enabled" 1

bspc monitor -d web-p web-s mail dev dsc img vid conf

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Thunderbird desktop='mail'
bspc rule -a discord desktop='dsc'
bspc rule -a Gimp desktop='img'
bspc rule -a mpv desktop='vid' follow=on
bspc rule -a zoom desktop='conf' follow=on
