#! /bin/sh

# set wallpaper
xwallpaper --zoom "$HOME/pictures/genome-wallpaper.png"

# set x resources
xrdb "$HOME/.Xresources"

# Launch all the background programs.
pidof sxhkd || sxhkd &
pidof dunst || dunst &
pidof blugon || blugon &
pidof emacs || emacs --daemon &
pidof nm-applet || nm-applet &
# pidof picom || picom &
# pidof bspswallow || bspswallow &
pidof polybar && killall polybar
polybar main &

# Disable Trackpad
# touchPadID=$(xinput | grep "TouchPad" | awk '{print substr($6,4,2)}')
# xinput set-prop $touchPadID "Device Enabled" 1

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8

bspc config border_width                3
bspc config top_padding                 18
bspc config right_padding               0
bspc config left_padding                0
bspc config bottom_padding              0
bspc config window_gap                  18
bspc config top_monocle_padding         0
bspc config right_monocle_padding       0
bspc config left_monocle_padding        0
bspc config bottom_monocle_padding      0

bspc config focused_border_color        $(xrdb -query | grep "color4" | cut -f 2)
bspc config normal_border_color         $(xrdb -query | grep "color0" | cut -f 2)
bspc config active_border_color         $(xrdb -query | grep "color0" | cut -f 2)
bspc config presel_feedback_color       $(xrdb -query | grep "color4" | cut -f 2)
bspc config split_ratio                 0.50
bspc config borderless_monocle          false
bspc config gapless_monocle             false
bspc config focus_follows_pointer       false

###Rules
# Cleanup
bspc rule -r '*'

# State rules
bspc rule -a Emacs state=tiled
bspc rule -a discord desktop='5'
bspc rule -a Gimp desktop='7'
bspc rule -a zoom desktop='8' follow=on
