export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg/"

export XDG_DATA_DIRS="$HOME/.guix-home/profile/share:$XDG_DATA_DIRS"
export XDG_CONFIG_DIRS="$HOME/.guix-home/profile/etc/xdg:$XDG_CONFIG_DIRS"

export GEM_PATH="$HOME/.local/share/gem"

export GUILE_LOAD_PATH=$XDG_CONFIG_HOME/guix/current/share/guile/site/3.0:$GUILE_LOAD_PATH
export GUILE_LOAD_COMPILED_PATH=$XDG_CONFIG_HOME/guix/current/lib/guile/3.0/site-ccache:$GUILE_LOAD_COMPILED_PATH

export PATH=$HOME/.local/bin/:$PATH

GUIX_PROFILE="$HOME/.guix-profile"
[ -f "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"