#! /bin/sh

target_file="/home/tassos/.config/alacritty/alacritty.yml"
xresources_file=$XDG_CONFIG_HOME/Xresources

xrdb $xresources_file

if test -d $target_file; then
    rm $target_file
fi

cp $target_file.in $target_file.tmp

for i in {0..15}
do
    v=`xrdb -query | awk '/*.color'"$i":'/{ print substr($2,2) }'`
    #echo $v
    eval "sed -i 's/%cl${i}%/\x270x${v}\x27/g' $target_file.tmp";
done

foreground=`xrdb -query | awk '/*.foreground/ { print substr($2,2) }'`
background=`xrdb -query | awk '/*.background/ { print substr($2,2) }'`
sed -i "s/%clfg%/\x270x${foreground}\x27/g" $target_file.tmp
sed -i "s/%clbg%/\x270x${background}\x27/g" $target_file.tmp

# Finally, replace target file with our updated one
if test -d $target_file; then
   rm $target_file
fi

mv $target_file.tmp $target_file

