#! /bin/sh

current_win_id=$(bspc query -N -n)
wm_class=$(xprop -id $current_win_id "WM_CLASS")
app_name=$(echo $wm_class | cut -d '"' -f2)

if [ $app_name = "emacs" ]; then
    current_file=$(emacsclient -e "(current-directory)" | cut -d '"' -f2)
    if [ $current_file != "nil" ]; then
	alacritty --working-directory=$current_file &
    else
	alacritty &
    fi
else
    alacritty &
fi
