#! /bin/sh

xresources=$XDG_CONFIG_HOME/Xresources
schemes_dir=$XDG_CONFIG_HOME/colorschemes

if [ $# -ne 0 ]; then
    # Get the colorscheme from the argument.
    if test -e $schemes_dir/$1; then
	chosen=$1
    else
	echo "Bad Arguments"
	exit 1
    fi
else
    # Get a chosen colorscheme from dmenu.
    choices=$(ls $schemes_dir | sed 's/ /\n/' -)
    chosen=$(echo -e "$choices" | dmenu -i -l 4)
fi

# Get the wallpaper of the color scheme and set it.
wallpaper=$(awk '/wallpaper/' $schemes_dir/$chosen | sed 's/.*://')
echo "Setting ${wallpaper} as the wallpaper." 
xwallpaper --zoom $wallpaper

# Reformat Xresources
line_num=$(awk '/color0/{ print NR; exit }' $xresources)

sed "$line_num,\${/.*/d}" $xresources > $xresources.tmp
cat $schemes_dir/$chosen >> $xresources.tmp

if test -d $xresources; then
    rm $xresources
fi

mv $xresources.tmp $xresources

# Read Xresources and reload window manager.
xrdb $xresources

# Colorize the terminal emulator.
colorizeAlacritty

# Reload the status bar.
if pidof polybar; then
    killall polybar
    polybar bar0 &
fi
