#! /bin/sh

choices="euro\ndvorak\ncolemak\nel"

if [ $# -ne 0 ]; then
    # Get the colorscheme from the argument.
    if [[ $choices =~ $1 ]]; then
        chosen=$1
    else
        echo "Bad Arguments"
	    exit 1
    fi
else
    # Get a chosen colorscheme from dmenu.
    chosen=$(echo -e "$choices" | dmenu)
fi

# This only changes the xorg keymap. Currently rolling with default
# qwerty for console.

if [ $chosen == "el" ]; then
    setxkbmap el
else
    setxkbmap us
    setxkbmap -variant $chosen
fi

# This is only temporary. Might change permissions to make it
# permenant.
# loadkeys $chosen 
