;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        end-of-buffer
        goto-line
        haskell-indentation-common-electric-command
        indent-for-tab-command
        kill-region
        mark-sexp
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-open-line
        org-return-and-maybe-indent
        org-self-insert-command
        org-shifttab
        org-yank
        overwrite-mode
        reindent-then-newline-and-indent
        transpose-words
        wdired-downcase-word
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        calc-dispatch
        handle-switch-frame
        indent-region
        ))
